name: "PR Triage"
on:
  workflow_call:

jobs:
  # https://github.com/marketplace/actions/auto-author-assign
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: "Assign Author to PR"
        uses: toshimaru/auto-author-assign@v1.6.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
