name: Check and Create PR CODEOWNERS

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  copy_codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/.github
          token: ${{ secrets.TOKEN1 }}

      - name: Install dependencies
        shell: bash
        run: npm install @actions/core @actions/github
        working-directory: ./action

      - name: Check and copy CODEOWNERS
        uses: ./action
        with:
          github-token: ${{secrets.TOKEN1}}
          source-repo: .github
