name: Check and Copy CODEOWNERS

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  copy_codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Check and copy CODEOWNERS
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.TOKEN1}}
          script: |
            const org = context.repo.owner;
            const sourceRepo = '.github';

            // Fetch the content of the CODEOWNERS file from the source repository
            let sourceContent;
            try {
              sourceContent = await github.repos.getContent({
                owner: org,
                repo: sourceRepo,
                path: 'CODEOWNERS',
              });
            } catch (error) {
              console.log(`Cannot find CODEOWNERS in ${sourceRepo}`);
              return;
            }

            // Decode the content from base64
            const decodedContent = Buffer.from(sourceContent.data.content, 'base64').toString(); 

            const repos = await github.paginate(github.repos.listForOrg, {
              org,
              type: 'all',
            });

            for (const repo of repos) {
              if (repo.name !== sourceRepo) {
                try {
                  await github.repos.getContent({
                    owner: org,
                    repo: repo.name,
                    path: 'CODEOWNERS',
                  });
                } catch (error) {
                  if (error.status === 404) {
                    // Get default branch
                    const { data: { default_branch } } = await github.repos.get({
                      owner: org,
                      repo: repo.name,
                    });

                    // Create a new branch
                    const { data: ref } = await github.git.getRef({
                      owner: org,
                      repo: repo.name,
                      ref: `heads/${default_branch}`,
                    });

                    const branchName = 'add-codeowners-branch2';
                    await github.git.createRef({
                      owner: org,
                      repo: repo.name,
                      ref: `refs/heads/${branchName}`,
                      sha: ref.object.sha,
                    });

                    // Create CODEOWNERS file in the new branch
                    await github.repos.createOrUpdateFileContents({
                      owner: org,
                      repo: repo.name,
                      path: 'CODEOWNERS',
                      message: 'T3456: Create CODEOWNERS',
                      content: Buffer.from(decodedContent).toString('base64'),
                      branch: branchName,
                    });

                    // Create a pull request
                    let targetBranch = default_branch;
                    if (default_branch === 'sagitta' || default_branch === 'equleuus') {
                      targetBranch = default_branch;
                    }

                    await github.pulls.create({
                      owner: org,
                      repo: repo.name,
                      title: 'T3456: Add CODEOWNERS file',
                      head: branchName,
                      base: targetBranch,
                    });
                  }
                }
              }
            }