name: check for codeowners file existence

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  copy_codeowners: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/.github
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check and copy CODEOWNERS
        uses: ./actions/codeowners-existence
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source-repo: .github
