---
  name: Darker-Ruff Lint
  
  on:
    workflow_call:
  
  jobs:
    darker-ruff-lint:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: read
      steps:
        - name: Checkout head
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            fetch-tags: true
            ref: ${{ github.event.pull_request.head.ref }}
            repository: ${{ github.event.pull_request.head.repo.full_name }}
  
        - name: Fetch base
          run: |
            git fetch https://github.com/${{ github.event.pull_request.base.repo.full_name }} ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/base
  
        - name: darker install
          run: |
            pip install git+https://github.com/akaihola/darker.git@master ruff>=0.0.292
  
        # - name: Show Ruff Configuration
        #   run: |
        #     echo "Ruff Conf in root repo"
        #     ruff check . --show-settings --config ./ruff.toml

        - name: Analyze Code
          run: |
            darker -r origin/base --check --diff --lint "ruff check --config .github/workflows/ruff.toml" --color .
            # darker -r origin/base --check --diff --lint "ruff check --config ./ruff.toml" --color .
            # darker -r origin/base --check --diff --lint "ruff check --config .config/ruff.toml" --color .
            # darker -r origin/base --check --diff --lint "ruff check" --color .
