---
    name: Darker-Ruff Lint
    
    on:
      workflow_call:
    
    env:
      base_ref: ${{ github.event.pull_request.base.ref }}
    
    jobs:
      darker-lint:
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
          contents: read
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
              ref: ${{ github.event.pull_request.head.ref }}
    
          - uses: actions/setup-python@v5
    
          - name: darker ruff install
            run: |
              pip install git+https://github.com/akaihola/darker.git@master ruff>=0.0.292
    
          - name: Fetch base branch
            run: |
              echo "Fetching base branch: ${base_ref}"
              git fetch origin ${base_ref}:refs/remotes/origin/${base_ref}            
            #   git fetch origin ${base_ref}:${base_ref}            

          - name: Debug Base Ref
            run: |
              echo "Base ref: ${base_ref}"
              git branch -r

          - name: Verify Base Branch
            run: |
              echo "Verifying base branch: refs/remotes/origin/${base_ref}"
              git show-ref refs/remotes/origin/${base_ref}              
    
          - name: Lint Code
            run: |
              echo "Running Lint"
              darker --revision refs/remotes/origin/${base_ref} --check --diff --lint "ruff check" --color . || echo "Darker command failed"
            #   darker --revision ${base_ref} --check --diff --lint "ruff check" --color . || echo "Darker command failed"
            #   darker -r refs/remotes/origin/${base_ref} --check --diff --lint "ruff check" --color .
            #   darker -r origin/${{ github.event.pull_request.base.ref }} --check --diff --lint "ruff check" --color .
            #   darker -r origin/${base_ref} --check --diff --lint "ruff check" --color . | grep '\[ruff\]'
            #   darker -r ${base_ref} --check --diff --lint "ruff check" --color . | grep '\[ruff\]'
            #   darker -r ${base_ref} --check --diff --lint "ruff check" --color .
            # darker -r ${base_ref} --check --diff --lint "ruff check" --color . 2>&1 | tee /dev/tty | grep '\[ruff\]'
