---
    name: Trigger PR
    
    on:
      workflow_call:
        secrets:
          REMOTE_OWNER:
            description: 'Remote repo owner'
            required: true
          REMOTE_REPO:
            description: 'Remote repo name'
            required: true
          PAT:
            description: 'Personal Access Token'
            required: true
    
    jobs:
      trigger-repo-sync:
        if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
    
          - name: Trigger PR
            shell: bash
            run: |
              echo "Triggering PR workflow for ${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REPO }}"
              echo "Triggering PR workflow with PAT ${{ secrets.PAT }}"
              curl -X POST \
                -H "Accept: application/vnd.github.everest-preview+json" \
                -H "Authorization: Bearer ${{ secrets.PAT }}" \
                https://api.github.com/repos/${{ secrets.REMOTE_OWNER }}/${{ secrets.REMOTE_REPO }}/actions/workflows/create-pr.yml/dispatches \
                -d '{"ref":"git-actions"}'