name: Validate python code using darker and ruff

on:
  workflow_call:
    inputs:
      base_ref:
        required: true
        type: string
      head_ref:
        required: true
        type: string

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install black ruff darker

    - name: Fetch branches and checkout head_ref
      run: |
        BASE_REF=${{ inputs.base_ref }}
        HEAD_REF=${{ inputs.head_ref }}

        echo "Base ref: $BASE_REF"
        echo "Head ref: $HEAD_REF"
        
        if [ -z "$BASE_REF" ] || [ -z "$HEAD_REF" ]; then
          echo "Base and head refs must be specified."
          exit 1
        fi
        
        git fetch origin $BASE_REF --depth=1
        git fetch origin $HEAD_REF --depth=1
        git checkout $HEAD_REF

    - name: Format and check with Darker
      run: |
        BASE_REF=${{ inputs.base_ref }}
        darker . --revision origin/$BASE_REF --diff --check > darker_diff.txt

    - name: Check contents of darker_diff.txt
      run: |
        echo "Darker diff:"
        cat darker_diff.txt

    - name: Lint with Ruff
      run: |
        BASE_REF=${{ inputs.base_ref }}
        darker . --revision origin/$BASE_REF --diff --check | grep '^--- ' | awk '{print $2}' > modified_files.txt

        if [ -s modified_files.txt ]; then
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              ruff check "$file" || true
            else
              echo "File $file does not exist."
            fi
          done < modified_files.txt
        else
          echo "No Python files modified"
        fi