name: Validate python code using black and ruff

on:
  workflow_call:
    inputs:
      base_ref:
        required: true
        type: string
      head_ref:
        required: true
        type: string

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install black ruff darker

    - name: Get list of modified Python files
      run: |
        BASE_REF=${{ inputs.base_ref }}
        HEAD_REF=${{ inputs.head_ref }}

        echo "Base ref: $BASE_REF"
        echo "Head ref: $HEAD_REF"
        
        if [ -z "$BASE_REF" ] || [ -z "$HEAD_REF" ]; then
          echo "Base and head refs must be specified."
          exit 1
        fi
        
        git fetch origin $BASE_REF --depth=1
        git fetch origin $HEAD_REF --depth=1

        # Ensure the working directory is clean
        git reset --hard

        # Checkout the head ref
        git checkout $HEAD_REF

        # Use Darker to get the list of modified Python files
        darker --revision $BASE_REF..$HEAD_REF . --diff > modified_files.txt


    - name: Check contents of modified_files.txt
      run: |
        echo "Modified files:"
        cat modified_files.txt

    - name: Lint with Ruff
      run: |
        if [ -s modified_files.txt ]; then
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              ruff check "$file"
            else
              echo "File $file does not exist."
            fi
          done < modified_files.txt
        else
          echo "No Python files modified"
        fi