name: Validate python code using black and ruff

on:
  workflow_call:
    inputs:
      base_ref:
        description: 'The base branch to compare against'
        required: true
        default: 'current'
      head_ref:
        description: 'The head branch to compare'
        required: true
        default: 'black_and-ruff'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install black ruff

    - name: Get list of modified Python files
      id: git_diff
      run: |
        BASE_REF=${{ github.event.inputs.base_ref || github.base_ref }}
        HEAD_REF=${{ github.event.inputs.head_ref || github.head_ref }}
        
        if [ -z "$BASE_REF" ] || [ -z "$HEAD_REF" ]; then
          echo "Base and head refs must be specified."
          exit 1
        fi
        
        git fetch origin $BASE_REF --depth=1
        git fetch origin $HEAD_REF --depth=1
        git diff --name-only origin/$BASE_REF...origin/$HEAD_REF -- '*.py' > modified_files.txt

    - name: Check formatting with Black
      run: |
        if [ -s modified_files.txt ]; then
          xargs black --check < modified_files.txt
        else
          echo "No Python files modified"
        fi

    - name: Lint with Ruff
      run: |
        if [ -s modified_files.txt ]; then
          xargs ruff check < modified_files.txt
        else
          echo "No Python files modified"
        fi